import { Suspense } from 'react';
import { Jura } from 'next/font/google';
import './globals.scss';
import TranslaterProvider from '@/translater/i18Provider';
import { ModalProvider } from '@/hooks';
import Loading from './loading';
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";
import BackToTop from "@/components/ui/BackToTop";

// import { ReactNotifications } from 'react-notifications-component';

const jura = Jura({ subsets: ['latin'] })

export const metadata = {
  title: 'WebEvery',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  console.log(jura)
  return (
    <html >
      {/* <body className={jura.className} id="modal" > */}
      <body id="modal" >
        {/* <div > */}
        <TranslaterProvider>
      {/* <ReactNotifications/> */}
          <ModalProvider>
            <Header />
            <Suspense fallback={<Loading/>}>
              {children}
              <BackToTop />
              <Footer />  
            </Suspense>
          </ModalProvider>
      {/* </ReactNotifications> */}
          </TranslaterProvider>
          {/* </div> */}
      </body>
    </html>
  )
}
